GridLayout:
    rows: 4
    GridLayout:
        cols: 2

        Label:
            text: 'A'
            font_size: '100sp'

        Button:
            background_normal: 'img/dzwiek.png'
            size_hint: (None,None)
    Label:
        id: 'duza_litera'
        font_size: '300sp'

    GridLayout:
        cols: 3
        Label:
        Button:
            id: 'zamien_litere'
            background_normal: 'img/strzalki.png'
            size_hint: (None,None)
        Lebel: