GridLayout:
    rows: 2
    size_hint: (None, None)

    GridLayout:

        cols:3
        rows:2
        Label:
        Label:
            text: "DOPASUJ W PARY"
            font_size: 40
            height: 300
        Label:


    GridLayout:
        cols:3
        Label:
            text: "wynik: "
        Label:
            id: licznik
            text: "0"
            font_size:20
            height: 300
        Label:




